title: Tyler Cameron's Portfolio Website
name: Tyler Cameron
description: representing my digital projects
timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
 
